### ISSUE TITLE
readme.md for how use more explicit

### ISSUE THREAD

**Issue by johnfelipe** [alvarlagerlof/company-name-generator#5]
```
root@ubuntu20portatil:~/company-name-generator# n 14
  installing : node-v14.20.0
       mkdir : /usr/local/n/versions/node/14.20.0
       fetch : https://nodejs.org/dist/v14.20.0/node-v14.20.0-linux-x64.tar.xz
     copying : node/14.20.0
   installed : v14.20.0 (with npm 6.14.17)

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
If "node --version" shows the old version then start a new shell, or reset the location hash with:
hash -r  (for bash, zsh, ash, dash, and ksh)
rehash   (for csh and tcsh)
root@ubuntu20portatil:~/company-name-generator# npm i

up to date, audited 38 packages in 564ms

4 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

then put this

```
root@ubuntu20portatil:~/company-name-generator# npm run generate

> company-name-generator@1.0.0 generate
> node --max-old-space-size=4000 index.js

file:///root/company-name-generator/index.js:5
import syllable from "syllable";
       ^^^^^^^^
SyntaxError: The requested module 'syllable' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```

how solve?

**Comment by alvarlagerlof** [comment]
Fixed, it needed to be
`import syllable from "syllable";`

The main branch is now also called `main`, so please delete the local repo and clone again to get the fix!
